"""initial schema

Revision ID: b14fd4c0615e
Revises: 
Create Date: 2026-09-14 13:28:02.765822

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa


from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b14fd4c0615e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_table('campaigns',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('initial_email_subject', sa.String(length=512), nullable=False),
    sa.Column('initial_email_body', sa.Text(), nullable=False),
    sa.Column('ai_instructions', sa.Text(), nullable=True),
    sa.Column('qualification_questions', sa.Text(), nullable=True),
    sa.Column('follow_ups', sa.JSON(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('min_delay_minutes', sa.Integer(), nullable=False),
    sa.Column('max_delay_minutes', sa.Integer(), nullable=False),
    sa.Column('daily_max', sa.Integer(), nullable=False),
    sa.Column('sending_start_time', sa.Time(), nullable=True),
    sa.Column('sending_end_time', sa.Time(), nullable=True),
    sa.Column('sending_days', sa.String(length=64), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('ai_reply_mode', sa.String(length=16), nullable=False),
    sa.Column('ai_reply_min_delay_minutes', sa.Integer(), nullable=False),
    sa.Column('ai_reply_max_delay_minutes', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('email_accounts',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scope', sa.String(length=1024), nullable=True),
    sa.Column('history_id', sa.String(length=255), nullable=True),
    sa.Column('watch_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('watch_channel', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('sync_attempts', sa.Integer(), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_accounts_email'), 'email_accounts', ['email'], unique=True)
    op.create_table('notifications',
    sa.Column('notification_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('vendor_id', sa.String(length=36), nullable=True),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('telegram_sent', sa.Boolean(), nullable=False),
    sa.Column('telegram_error', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=1024), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_conversation_id'), 'notifications', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_vendor_id'), 'notifications', ['vendor_id'], unique=False)
    op.create_table('oauth_credentials',
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('account_email', sa.String(length=320), nullable=False),
    sa.Column('scope', sa.String(length=1024), nullable=True),
    sa.Column('token_encrypted', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_credentials_account_email'), 'oauth_credentials', ['account_email'], unique=False)
    op.create_index(op.f('ix_oauth_credentials_provider'), 'oauth_credentials', ['provider'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=16), nullable=False),
    sa.Column('section', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.create_index(op.f('ix_settings_section'), 'settings', ['section'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vendors',
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('trade', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=512), nullable=True),
    sa.Column('research_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('qualification_status', sa.String(length=32), nullable=False),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reply_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opted_out', sa.Boolean(), nullable=False),
    sa.Column('opted_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bounced', sa.Boolean(), nullable=False),
    sa.Column('bounced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_unsubscribed', sa.Boolean(), nullable=False),
    sa.Column('ai_paused', sa.Boolean(), nullable=False),
    sa.Column('human_handoff', sa.Boolean(), nullable=False),
    sa.Column('meeting_status', sa.String(length=32), nullable=True),
    sa.Column('email_domain', sa.String(length=255), nullable=True),
    sa.Column('normalized_email', sa.String(length=320), nullable=True),
    sa.Column('company_loc_key', sa.String(length=512), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_city'), 'vendors', ['city'], unique=False)
    op.create_index(op.f('ix_vendors_company'), 'vendors', ['company'], unique=False)
    op.create_index(op.f('ix_vendors_company_loc_key'), 'vendors', ['company_loc_key'], unique=False)
    op.create_index(op.f('ix_vendors_email'), 'vendors', ['email'], unique=False)
    op.create_index(op.f('ix_vendors_email_domain'), 'vendors', ['email_domain'], unique=False)
    op.create_index(op.f('ix_vendors_normalized_email'), 'vendors', ['normalized_email'], unique=False)
    op.create_index(op.f('ix_vendors_status'), 'vendors', ['status'], unique=False)
    op.create_index(op.f('ix_vendors_trade'), 'vendors', ['trade'], unique=False)
    op.create_table('campaign_vendors',
    sa.Column('campaign_id', sa.CHAR(length=36), nullable=False),
    sa.Column('vendor_id', sa.CHAR(length=36), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('initial_job_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'vendor_id', name='uq_campaign_vendor')
    )
    op.create_index(op.f('ix_campaign_vendors_campaign_id'), 'campaign_vendors', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_vendors_vendor_id'), 'campaign_vendors', ['vendor_id'], unique=False)
    op.create_table('conversations',
    sa.Column('vendor_id', sa.CHAR(length=36), nullable=False),
    sa.Column('campaign_id', sa.CHAR(length=36), nullable=True),
    sa.Column('email_account_id', sa.CHAR(length=36), nullable=True),
    sa.Column('gmail_thread_id', sa.String(length=255), nullable=True),
    sa.Column('gmail_message_id', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('ai_paused', sa.Boolean(), nullable=False),
    sa.Column('human_controlled', sa.Boolean(), nullable=False),
    sa.Column('handoff_reason', sa.Text(), nullable=True),
    sa.Column('qualification_status', sa.String(length=32), nullable=False),
    sa.Column('last_inbound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_outbound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_follow_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('follow_up_step', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['email_account_id'], ['email_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_campaign_id'), 'conversations', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_conversations_email_account_id'), 'conversations', ['email_account_id'], unique=False)
    op.create_index(op.f('ix_conversations_gmail_message_id'), 'conversations', ['gmail_message_id'], unique=False)
    op.create_index(op.f('ix_conversations_gmail_thread_id'), 'conversations', ['gmail_thread_id'], unique=True)
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_index(op.f('ix_conversations_vendor_id'), 'conversations', ['vendor_id'], unique=False)
    op.create_table('meetings',
    sa.Column('vendor_id', sa.CHAR(length=36), nullable=False),
    sa.Column('campaign_id', sa.CHAR(length=36), nullable=True),
    sa.Column('conversation_id', sa.CHAR(length=36), nullable=True),
    sa.Column('meeting_url', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('invitation_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_campaign_id'), 'meetings', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_meetings_conversation_id'), 'meetings', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_meetings_status'), 'meetings', ['status'], unique=False)
    op.create_index(op.f('ix_meetings_vendor_id'), 'meetings', ['vendor_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.CHAR(length=36), nullable=False),
    sa.Column('vendor_id', sa.CHAR(length=36), nullable=False),
    sa.Column('gmail_message_id', sa.String(length=255), nullable=True),
    sa.Column('gmail_thread_id', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=512), nullable=False),
    sa.Column('sender', sa.String(length=512), nullable=False),
    sa.Column('recipient', sa.String(length=512), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('delivery_state', sa.String(length=32), nullable=False),
    sa.Column('ai_used', sa.Boolean(), nullable=False),
    sa.Column('draft', sa.Boolean(), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_gmail_message_id'), 'messages', ['gmail_message_id'], unique=False)
    op.create_index(op.f('ix_messages_gmail_thread_id'), 'messages', ['gmail_thread_id'], unique=False)
    op.create_index(op.f('ix_messages_idempotency_key'), 'messages', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_messages_vendor_id'), 'messages', ['vendor_id'], unique=False)
    op.create_table('scheduled_jobs',
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('vendor_id', sa.CHAR(length=36), nullable=False),
    sa.Column('campaign_id', sa.CHAR(length=36), nullable=True),
    sa.Column('conversation_id', sa.CHAR(length=36), nullable=True),
    sa.Column('idempotency_key', sa.String(length=512), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('claim_uuid', sa.String(length=64), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('step', sa.Integer(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_jobs_campaign_id'), 'scheduled_jobs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_scheduled_jobs_conversation_id'), 'scheduled_jobs', ['conversation_id'], unique=False)
    op.create_index('ix_scheduled_jobs_due_status', 'scheduled_jobs', ['run_after', 'status'], unique=False)
    op.create_index(op.f('ix_scheduled_jobs_idempotency_key'), 'scheduled_jobs', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_scheduled_jobs_status'), 'scheduled_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_scheduled_jobs_vendor_id'), 'scheduled_jobs', ['vendor_id'], unique=False)
    op.create_index('ix_scheduled_jobs_vendor_type', 'scheduled_jobs', ['vendor_id', 'job_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scheduled_jobs_vendor_type', table_name='scheduled_jobs')
    op.drop_index(op.f('ix_scheduled_jobs_vendor_id'), table_name='scheduled_jobs')
    op.drop_index(op.f('ix_scheduled_jobs_status'), table_name='scheduled_jobs')
    op.drop_index(op.f('ix_scheduled_jobs_idempotency_key'), table_name='scheduled_jobs')
    op.drop_index('ix_scheduled_jobs_due_status', table_name='scheduled_jobs')
    op.drop_index(op.f('ix_scheduled_jobs_conversation_id'), table_name='scheduled_jobs')
    op.drop_index(op.f('ix_scheduled_jobs_campaign_id'), table_name='scheduled_jobs')
    op.drop_table('scheduled_jobs')
    op.drop_index(op.f('ix_messages_vendor_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_idempotency_key'), table_name='messages')
    op.drop_index(op.f('ix_messages_gmail_thread_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_gmail_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_meetings_vendor_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_status'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_conversation_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_campaign_id'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_conversations_vendor_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_gmail_thread_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_gmail_message_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_email_account_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_campaign_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_campaign_vendors_vendor_id'), table_name='campaign_vendors')
    op.drop_index(op.f('ix_campaign_vendors_campaign_id'), table_name='campaign_vendors')
    op.drop_table('campaign_vendors')
    op.drop_index(op.f('ix_vendors_trade'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_status'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_normalized_email'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_email_domain'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_email'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_company_loc_key'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_company'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_city'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_settings_section'), table_name='settings')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_oauth_credentials_provider'), table_name='oauth_credentials')
    op.drop_index(op.f('ix_oauth_credentials_account_email'), table_name='oauth_credentials')
    op.drop_table('oauth_credentials')
    op.drop_index(op.f('ix_notifications_vendor_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_conversation_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_email_accounts_email'), table_name='email_accounts')
    op.drop_table('email_accounts')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###