# TLS listener - GENERATED by scripts/install.sh from ssl.conf.tpl.
# __DOMAIN__ is replaced with the real domain; the result is written to
# infra/nginx/conf.d/ssl.conf (git-ignored). Do not edit ssl.conf directly.
server {
    listen 443 ssl;
    http2 on;
    server_name __DOMAIN__;

    # Certificates live in the host dir infra/certs/etc/letsencrypt, which the
    # reverse-proxy container mounts read-only at /etc/letsencrypt.
    ssl_certificate     /etc/letsencrypt/live/__DOMAIN__/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/__DOMAIN__/privkey.pem;

    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 10m;

    # HSTS: tell browsers to only use HTTPS for this domain.
    add_header Strict-Transport-Security "max-age=31536000" always;

    # ---- API ----
    location /api/ {
        proxy_pass http://api:8000;
        include /etc/nginx/conf.d/proxy_headers.conf;
        proxy_connect_timeout 10s;
        proxy_read_timeout 120s;
    }

    # ---- Health / readiness probes ----
    location = /health {
        proxy_pass http://api:8000/health;
        proxy_set_header Host $host;
        access_log off;
    }
    location = /ready {
        proxy_pass http://api:8000/ready;
        proxy_set_header Host $host;
        access_log off;
        proxy_read_timeout 10s;
    }

    # ---- Frontend ----
    location / {
        proxy_pass http://frontend:3000;
        include /etc/nginx/conf.d/proxy_headers.conf;
        proxy_connect_timeout 10s;
        proxy_read_timeout 60s;
    }
}